[[headers]]
  for = "/.well-known/apple-app-site-association"
  [headers.values]
    Cache-Control = "public, max-age=0"
    Content-Type = "application/pkcs7-mime"
    X-Content-Type-Options = "nosniff"

[[plugins]]
  package = "@netlify/plugin-nextjs"