export const pricingModels = [
  {
    name: 'Free',
    title: 'Free Plan',
    description: 'Get started with essential features.',
    identifier: 'Basic',
    level: 1,
    pricing: {
      // title: 'Best value',
      price: 'FREE',
      value: 0,
      description: 'No credit card needed, no feature limitations',
    },
    usage: {
      create_business: 1,
      create_team: 1,
      withdrawal_account: 1,
      extensive_reporting: false,
      create_discounts: false,
    },
    perks: [
      {
        title: '1 business account',
        description: 'Start your ventures with a limit of two businesses.',
      },
      {
        title: '2 team members',
        description: 'Collaborate effectively with a small team.',
      },
      {
        title: '1 withdrawal account',
        description: 'Receive assistance with basic inquiries and issues.',
      },
      {
        title: 'Basic reporting',
        description: 'Enjoy discounted rates for the first three months.',
      },
      {
        title: '2% flat rate on every booking after 5 free bookings',
      },
      {
        title: 'Same day Email and Chat support',
      },
    ],
  },
  {
    name: 'Starter',
    title: 'Starter Plan',
    description: 'Our most popular plan with enhanced features.',
    identifier: 'Starter',
    level: 2,
    pricing: {
      title: 'Most popular',
      price: '₦40,000/mo',
      value: 40000,
      description: '',
    },
    perkTitle: 'Everything in Basic, plus:',
    usage: {
      create_business: 2,
      create_team: 30,
      withdrawal_account: 2,
      extensive_reporting: true,
      create_discounts: false,
    },
    perks: [
      {
        title: 'Add multiple business locations',
        description:
          'Expand your business portfolio with up to two businesses.',
      },
      {
        title: 'Cash at hand payment',
        description: 'Grow your team while maintaining efficiency.',
      },
      {
        title: 'Personalized customer booking portal',
        description:
          'Access detailed insights and reports to optimize performance.',
      },
      {
        title: 'Unlimited team members',
        description: 'Receive faster response times and dedicated support.',
      },
      {
        title: 'Extensive reports',
      },
      {
        title: 'Show in group Ads',
      },
    ],
  },
  {
    name: 'Business',
    title: 'Business Plan',
    identifier: 'Business',
    description: 'Premium features for established enterprises.',
    level: 3,
    pricing: {
      title: 'Premium',
      price: '₦100,000/mo',
      value: 100000,
      description: '',
    },
    perkTitle: 'Everything in Starter, plus:',
    usage: {
      create_business: 'Unlimited',
      create_team: 'Unlimited',
      withdrawal_account: 'Unlimited',
      extensive_reporting: true,
      create_discounts: true,
    },
    perks: [
      {
        title: '2 withdrawal accounts',
        description: 'Manage multiple business entities seamlessly.',
      },
      {
        title: 'Customized receipts',
        description: 'Scale your operations with additional team members.',
      },
      {
        title: 'Create coupons and discounts',
        description: 'Personalize your platform with custom branding features.',
      },
      {
        title: 'Access to sell on marketplace',
        description: 'Access a dedicated manager for personalized assistance.',
      },
    ],
  },
]

export const Permissions = {
  Manager: [
    'businesses:view',
    'teams:view',
    'bookings:view',
    'users:view',
    'users:create',
    'users:update',
    'users:delete',
    'transactions:view',
  ],
  Staff: [
    'users:view',
    'users:create',
    'users:update',
    'users:delete',
    'bookings:view',
    'transactions:view',
  ],
  User: [
    'users:view',
    'users:create',
    'users:update',
    'users:delete',
    'businesses:view',
    'bookings:view',
    'bookings:create',
    'bookings:update',
    'bookings:delete',
    'transactions:view',
    'transactions:create',
    'transactions:update',
    'amenities:view',
    'categories:view',
    'reviews:view',
    'reviews:create',
    'insights:view',
    'reports:view',
    'settings:view',
    'settings:update',
    'notifications:view',
    'notifications:create',
    'notifications:update',
    'messages:view',
    'messages:create',
    'messages:update',
    'discounts:view',
    'device-token:view',
    'device-token:create',
    'device-token:update',
    'device-token:delete',
  ],
  Owner: [
    'businesses:create',
    'businesses:update',
    'businesses:delete',
    'amenities:create',
    'amenities:update',
    'amenities:delete',
    'categories:create',
    'categories:update',
    'categories:delete',
    'people:view',
    'reviews:view',
    'transactions:view',
    'accounts:view',
    'accounts:create',
    'accounts:update',
    'accounts:delete',
    'withdrawal:view',
    'withdrawal:create',
    'withdrawal:update',
    'withdrawal:delete',
    'banks:view',
    'banks:create',
    'banks:update',
    'banks:delete',
    'discounts:view',
    'discounts:create',
    'discounts:update',
    'discounts:delete',
    'service-groups:view',
    'service-groups:create',
    'service-groups:update',
    'service-groups:delete',
    'teams:view',
    'teams:create',
    'teams:update',
    'teams:delete',
  ],
}

export const colors = {
  transparent: 'transparent',
  white: '#fff',
  lightgrey: '#B4B4B8',
  primary: '#389abf',
  accent_blue: '#389abf',
  secondary: '#D1F3EC',
  black: '#202020',
  purple: '#E85187',
  lightblack: '#0e0e0e6d',
  danger: '#ED254E',
  gold: '#F9DC5C',
  lightgreen: '#D1F3EC',
  lightprimary: '#ebf5fb',
  lightpurple: '#ffebe7',
  dashgrey: '#f7f7f9',
  chartColor: '#e95087',
  upcomingColor: '#fff5e0',
  upcomingTextColor: '#a47120',
  happeningColor: '#edf3e8',
  happeningTextColor: '#517143',
  gray: '#e6e6e8',
  green: '#10b981',
}
